### ISSUE TITLE
error gradio

### ISSUE THREAD

**Issue by coderwpf** [esnya/realtime-whisper#1]
python -m realtime_whisper --gradio-launch
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/root/anaconda3/envs/esnya-realtime-whisper/lib/python3.11/site-packages/realtime_whisper/__main__.py", line 87, in <module>
    asyncio.run(cli())
  File "/home/root/anaconda3/envs/esnya-realtime-whisper/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/root/anaconda3/envs/esnya-realtime-whisper/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/root/anaconda3/envs/esnya-realtime-whisper/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/root/anaconda3/envs/esnya-realtime-whisper/lib/python3.11/site-packages/realtime_whisper/__main__.py", line 42, in cli
    GradioInterface(config.gradio, config.transcription.sampling_rate)
  File "/home/root/anaconda3/envs/esnya-realtime-whisper/lib/python3.11/site-packages/realtime_whisper/speech_transcription_interfaces/gradio_interface.py", line 30, in __init__
    gr.Audio(
  File "/home/root/anaconda3/envs/esnya-realtime-whisper/lib/python3.11/site-packages/gradio/component_meta.py", line 152, in wrapper
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

**Comment by buaajjg** [comment]
gradio version issue ,  change  your gradio  version  to 3.50.2

**Comment by esnya** [comment]
同種のGradio不具合は #6 へ集約しました。このissueはduplicateとしてcloseします。再現情報は #6 で引き続き扱います。
